services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" 
    volumes:
      - .:/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  phpfpm:
    image: php:8.3-fpm
    volumes:
      - .:/app
